import fs from 'node:fs';
import path from 'node:path';
import { config } from 'dotenv';

// Load environment variables from .env file
config();

const outPath = path.resolve(process.cwd(), 'public', 'env.js');

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || '';

const contents = [
  '// Generated by scripts/generate-env-js.mjs',
  `window.__SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};`,
  `window.__SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};`,
  '' // trailing newline
].join('\n');

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, contents, 'utf8');
console.log('[build] Wrote public/env.js');


